import {
  Sparkles,
  Image,
  Video,
  FileText,
  Mic,
  GraduationCap,
  PenTool,
  Briefcase,
  FlaskConical,
  Code2,
  Languages,
  BarChart3,
  Heart,
  Lightbulb,
  BookOpen,
  Mail,
  FileCheck,
  Search,
  Brain,
  Palette,
  Globe,
  Calculator,
  MessageSquare,
  Newspaper,
  ClipboardList,
  Utensils,
  TrendingUp,
  Dumbbell,
  Plane,
  Presentation,
  Scale,
  Stethoscope,
} from "lucide-react";

// ==================== 类型定义 ====================
interface Template {
  icon: any;
  titleKey: string;
  descKey: string;
  promptKey: string;
  color: string;
  bgColor: string;
}

interface Category {
  id: string;
  labelKey: string;
  emoji: string;
  templates: Template[];
}

// ==================== 分类与模板定义 ====================
export const CATEGORIES: Category[] = [
    {
      id: "hot",
      labelKey: "chat.emptyState.categories.hot",
      emoji: "🔥",
      templates: [
        {
          icon: Brain,
          titleKey: "chat.emptyState.tpl.deepResearch.title",
          descKey: "chat.emptyState.tpl.deepResearch.desc",
          promptKey: "chat.emptyState.tpl.deepResearch.prompt",
          color: "text-violet-600 dark:text-violet-400",
          bgColor: "bg-violet-50 dark:bg-violet-950/20",
        },
        {
          icon: Image,
          titleKey: "chat.emptyState.tpl.imageAnalysis.title",
          descKey: "chat.emptyState.tpl.imageAnalysis.desc",
          promptKey: "chat.emptyState.tpl.imageAnalysis.prompt",
          color: "text-blue-600 dark:text-blue-400",
          bgColor: "bg-blue-50 dark:bg-blue-950/20",
        },
        {
          icon: PenTool,
          titleKey: "chat.emptyState.tpl.writeEssay.title",
          descKey: "chat.emptyState.tpl.writeEssay.desc",
          promptKey: "chat.emptyState.tpl.writeEssay.prompt",
          color: "text-emerald-600 dark:text-emerald-400",
          bgColor: "bg-emerald-50 dark:bg-emerald-950/20",
        },
        {
          icon: Code2,
          titleKey: "chat.emptyState.tpl.codeHelp.title",
          descKey: "chat.emptyState.tpl.codeHelp.desc",
          promptKey: "chat.emptyState.tpl.codeHelp.prompt",
          color: "text-cyan-600 dark:text-cyan-400",
          bgColor: "bg-cyan-50 dark:bg-cyan-950/20",
        },
        {
          icon: Video,
          titleKey: "chat.emptyState.tpl.generateVideo.title",
          descKey: "chat.emptyState.tpl.generateVideo.desc",
          promptKey: "chat.emptyState.tpl.generateVideo.prompt",
          color: "text-purple-600 dark:text-purple-400",
          bgColor: "bg-purple-50 dark:bg-purple-950/20",
        },
        {
          icon: Languages,
          titleKey: "chat.emptyState.tpl.translate.title",
          descKey: "chat.emptyState.tpl.translate.desc",
          promptKey: "chat.emptyState.tpl.translate.prompt",
          color: "text-sky-600 dark:text-sky-400",
          bgColor: "bg-sky-50 dark:bg-sky-950/20",
        },
      ],
    },
    {
      id: "education",
      labelKey: "chat.emptyState.categories.education",
      emoji: "🎓",
      templates: [
        {
          icon: FileCheck,
          titleKey: "chat.emptyState.tpl.homeworkCorrection.title",
          descKey: "chat.emptyState.tpl.homeworkCorrection.desc",
          promptKey: "chat.emptyState.tpl.homeworkCorrection.prompt",
          color: "text-red-600 dark:text-red-400",
          bgColor: "bg-red-50 dark:bg-red-950/20",
        },
        {
          icon: GraduationCap,
          titleKey: "chat.emptyState.tpl.examPrep.title",
          descKey: "chat.emptyState.tpl.examPrep.desc",
          promptKey: "chat.emptyState.tpl.examPrep.prompt",
          color: "text-blue-600 dark:text-blue-400",
          bgColor: "bg-blue-50 dark:bg-blue-950/20",
        },
        {
          icon: BookOpen,
          titleKey: "chat.emptyState.tpl.studyPlan.title",
          descKey: "chat.emptyState.tpl.studyPlan.desc",
          promptKey: "chat.emptyState.tpl.studyPlan.prompt",
          color: "text-indigo-600 dark:text-indigo-400",
          bgColor: "bg-indigo-50 dark:bg-indigo-950/20",
        },
        {
          icon: Lightbulb,
          titleKey: "chat.emptyState.tpl.conceptExplain.title",
          descKey: "chat.emptyState.tpl.conceptExplain.desc",
          promptKey: "chat.emptyState.tpl.conceptExplain.prompt",
          color: "text-amber-600 dark:text-amber-400",
          bgColor: "bg-amber-50 dark:bg-amber-950/20",
        },
        {
          icon: Calculator,
          titleKey: "chat.emptyState.tpl.mathSolver.title",
          descKey: "chat.emptyState.tpl.mathSolver.desc",
          promptKey: "chat.emptyState.tpl.mathSolver.prompt",
          color: "text-teal-600 dark:text-teal-400",
          bgColor: "bg-teal-50 dark:bg-teal-950/20",
        },
        {
          icon: MessageSquare,
          titleKey: "chat.emptyState.tpl.englishPractice.title",
          descKey: "chat.emptyState.tpl.englishPractice.desc",
          promptKey: "chat.emptyState.tpl.englishPractice.prompt",
          color: "text-green-600 dark:text-green-400",
          bgColor: "bg-green-50 dark:bg-green-950/20",
        },
        {
          icon: ClipboardList,
          titleKey: "chat.emptyState.tpl.quizGenerator.title",
          descKey: "chat.emptyState.tpl.quizGenerator.desc",
          promptKey: "chat.emptyState.tpl.quizGenerator.prompt",
          color: "text-orange-600 dark:text-orange-400",
          bgColor: "bg-orange-50 dark:bg-orange-950/20",
        },
        {
          icon: BookOpen,
          titleKey: "chat.emptyState.tpl.readingComprehension.title",
          descKey: "chat.emptyState.tpl.readingComprehension.desc",
          promptKey: "chat.emptyState.tpl.readingComprehension.prompt",
          color: "text-rose-600 dark:text-rose-400",
          bgColor: "bg-rose-50 dark:bg-rose-950/20",
        },
      ],
    },
    {
      id: "writing",
      labelKey: "chat.emptyState.categories.writing",
      emoji: "✍️",
      templates: [
        {
          icon: PenTool,
          titleKey: "chat.emptyState.tpl.writeEssay.title",
          descKey: "chat.emptyState.tpl.writeEssay.desc",
          promptKey: "chat.emptyState.tpl.writeEssay.prompt",
          color: "text-emerald-600 dark:text-emerald-400",
          bgColor: "bg-emerald-50 dark:bg-emerald-950/20",
        },
        {
          icon: Mail,
          titleKey: "chat.emptyState.tpl.writeEmail.title",
          descKey: "chat.emptyState.tpl.writeEmail.desc",
          promptKey: "chat.emptyState.tpl.writeEmail.prompt",
          color: "text-blue-600 dark:text-blue-400",
          bgColor: "bg-blue-50 dark:bg-blue-950/20",
        },
        {
          icon: Newspaper,
          titleKey: "chat.emptyState.tpl.writeCopy.title",
          descKey: "chat.emptyState.tpl.writeCopy.desc",
          promptKey: "chat.emptyState.tpl.writeCopy.prompt",
          color: "text-pink-600 dark:text-pink-400",
          bgColor: "bg-pink-50 dark:bg-pink-950/20",
        },
        {
          icon: FileText,
          titleKey: "chat.emptyState.tpl.weeklyReport.title",
          descKey: "chat.emptyState.tpl.weeklyReport.desc",
          promptKey: "chat.emptyState.tpl.weeklyReport.prompt",
          color: "text-slate-600 dark:text-slate-400",
          bgColor: "bg-slate-50 dark:bg-slate-950/20",
        },
        {
          icon: Sparkles,
          titleKey: "chat.emptyState.tpl.creativeStory.title",
          descKey: "chat.emptyState.tpl.creativeStory.desc",
          promptKey: "chat.emptyState.tpl.creativeStory.prompt",
          color: "text-purple-600 dark:text-purple-400",
          bgColor: "bg-purple-50 dark:bg-purple-950/20",
        },
        {
          icon: FileText,
          titleKey: "chat.emptyState.tpl.resumeOptimize.title",
          descKey: "chat.emptyState.tpl.resumeOptimize.desc",
          promptKey: "chat.emptyState.tpl.resumeOptimize.prompt",
          color: "text-cyan-600 dark:text-cyan-400",
          bgColor: "bg-cyan-50 dark:bg-cyan-950/20",
        },
        {
          icon: Palette,
          titleKey: "chat.emptyState.tpl.xiaohongshu.title",
          descKey: "chat.emptyState.tpl.xiaohongshu.desc",
          promptKey: "chat.emptyState.tpl.xiaohongshu.prompt",
          color: "text-red-600 dark:text-red-400",
          bgColor: "bg-red-50 dark:bg-red-950/20",
        },
        {
          icon: FileText,
          titleKey: "chat.emptyState.tpl.polishText.title",
          descKey: "chat.emptyState.tpl.polishText.desc",
          promptKey: "chat.emptyState.tpl.polishText.prompt",
          color: "text-violet-600 dark:text-violet-400",
          bgColor: "bg-violet-50 dark:bg-violet-950/20",
        },
      ],
    },
    {
      id: "work",
      labelKey: "chat.emptyState.categories.work",
      emoji: "💼",
      templates: [
        {
          icon: Presentation,
          titleKey: "chat.emptyState.tpl.pptOutline.title",
          descKey: "chat.emptyState.tpl.pptOutline.desc",
          promptKey: "chat.emptyState.tpl.pptOutline.prompt",
          color: "text-orange-600 dark:text-orange-400",
          bgColor: "bg-orange-50 dark:bg-orange-950/20",
        },
        {
          icon: ClipboardList,
          titleKey: "chat.emptyState.tpl.meetingSummary.title",
          descKey: "chat.emptyState.tpl.meetingSummary.desc",
          promptKey: "chat.emptyState.tpl.meetingSummary.prompt",
          color: "text-blue-600 dark:text-blue-400",
          bgColor: "bg-blue-50 dark:bg-blue-950/20",
        },
        {
          icon: TrendingUp,
          titleKey: "chat.emptyState.tpl.swotAnalysis.title",
          descKey: "chat.emptyState.tpl.swotAnalysis.desc",
          promptKey: "chat.emptyState.tpl.swotAnalysis.prompt",
          color: "text-green-600 dark:text-green-400",
          bgColor: "bg-green-50 dark:bg-green-950/20",
        },
        {
          icon: Briefcase,
          titleKey: "chat.emptyState.tpl.projectPlan.title",
          descKey: "chat.emptyState.tpl.projectPlan.desc",
          promptKey: "chat.emptyState.tpl.projectPlan.prompt",
          color: "text-indigo-600 dark:text-indigo-400",
          bgColor: "bg-indigo-50 dark:bg-indigo-950/20",
        },
        {
          icon: Scale,
          titleKey: "chat.emptyState.tpl.contractReview.title",
          descKey: "chat.emptyState.tpl.contractReview.desc",
          promptKey: "chat.emptyState.tpl.contractReview.prompt",
          color: "text-amber-600 dark:text-amber-400",
          bgColor: "bg-amber-50 dark:bg-amber-950/20",
        },
        {
          icon: MessageSquare,
          titleKey: "chat.emptyState.tpl.interviewPrep.title",
          descKey: "chat.emptyState.tpl.interviewPrep.desc",
          promptKey: "chat.emptyState.tpl.interviewPrep.prompt",
          color: "text-teal-600 dark:text-teal-400",
          bgColor: "bg-teal-50 dark:bg-teal-950/20",
        },
      ],
    },
    {
      id: "research",
      labelKey: "chat.emptyState.categories.research",
      emoji: "🔬",
      templates: [
        {
          icon: Brain,
          titleKey: "chat.emptyState.tpl.deepResearch.title",
          descKey: "chat.emptyState.tpl.deepResearch.desc",
          promptKey: "chat.emptyState.tpl.deepResearch.prompt",
          color: "text-violet-600 dark:text-violet-400",
          bgColor: "bg-violet-50 dark:bg-violet-950/20",
        },
        {
          icon: FlaskConical,
          titleKey: "chat.emptyState.tpl.paperAnalysis.title",
          descKey: "chat.emptyState.tpl.paperAnalysis.desc",
          promptKey: "chat.emptyState.tpl.paperAnalysis.prompt",
          color: "text-blue-600 dark:text-blue-400",
          bgColor: "bg-blue-50 dark:bg-blue-950/20",
        },
        {
          icon: Search,
          titleKey: "chat.emptyState.tpl.literatureReview.title",
          descKey: "chat.emptyState.tpl.literatureReview.desc",
          promptKey: "chat.emptyState.tpl.literatureReview.prompt",
          color: "text-indigo-600 dark:text-indigo-400",
          bgColor: "bg-indigo-50 dark:bg-indigo-950/20",
        },
        {
          icon: FileText,
          titleKey: "chat.emptyState.tpl.abstractWriting.title",
          descKey: "chat.emptyState.tpl.abstractWriting.desc",
          promptKey: "chat.emptyState.tpl.abstractWriting.prompt",
          color: "text-emerald-600 dark:text-emerald-400",
          bgColor: "bg-emerald-50 dark:bg-emerald-950/20",
        },
        {
          icon: BarChart3,
          titleKey: "chat.emptyState.tpl.dataInterpret.title",
          descKey: "chat.emptyState.tpl.dataInterpret.desc",
          promptKey: "chat.emptyState.tpl.dataInterpret.prompt",
          color: "text-cyan-600 dark:text-cyan-400",
          bgColor: "bg-cyan-50 dark:bg-cyan-950/20",
        },
        {
          icon: Lightbulb,
          titleKey: "chat.emptyState.tpl.researchProposal.title",
          descKey: "chat.emptyState.tpl.researchProposal.desc",
          promptKey: "chat.emptyState.tpl.researchProposal.prompt",
          color: "text-amber-600 dark:text-amber-400",
          bgColor: "bg-amber-50 dark:bg-amber-950/20",
        },
      ],
    },
    {
      id: "media",
      labelKey: "chat.emptyState.categories.media",
      emoji: "🎨",
      templates: [
        {
          icon: Image,
          titleKey: "chat.emptyState.tpl.imageAnalysis.title",
          descKey: "chat.emptyState.tpl.imageAnalysis.desc",
          promptKey: "chat.emptyState.tpl.imageAnalysis.prompt",
          color: "text-blue-600 dark:text-blue-400",
          bgColor: "bg-blue-50 dark:bg-blue-950/20",
        },
        {
          icon: Palette,
          titleKey: "chat.emptyState.tpl.imageGenerate.title",
          descKey: "chat.emptyState.tpl.imageGenerate.desc",
          promptKey: "chat.emptyState.tpl.imageGenerate.prompt",
          color: "text-pink-600 dark:text-pink-400",
          bgColor: "bg-pink-50 dark:bg-pink-950/20",
        },
        {
          icon: Video,
          titleKey: "chat.emptyState.tpl.generateVideo.title",
          descKey: "chat.emptyState.tpl.generateVideo.desc",
          promptKey: "chat.emptyState.tpl.generateVideo.prompt",
          color: "text-purple-600 dark:text-purple-400",
          bgColor: "bg-purple-50 dark:bg-purple-950/20",
        },
        {
          icon: Mic,
          titleKey: "chat.emptyState.tpl.voiceTranscribe.title",
          descKey: "chat.emptyState.tpl.voiceTranscribe.desc",
          promptKey: "chat.emptyState.tpl.voiceTranscribe.prompt",
          color: "text-orange-600 dark:text-orange-400",
          bgColor: "bg-orange-50 dark:bg-orange-950/20",
        },
        {
          icon: FileText,
          titleKey: "chat.emptyState.tpl.pdfSummary.title",
          descKey: "chat.emptyState.tpl.pdfSummary.desc",
          promptKey: "chat.emptyState.tpl.pdfSummary.prompt",
          color: "text-red-600 dark:text-red-400",
          bgColor: "bg-red-50 dark:bg-red-950/20",
        },
        {
          icon: Image,
          titleKey: "chat.emptyState.tpl.ocrExtract.title",
          descKey: "chat.emptyState.tpl.ocrExtract.desc",
          promptKey: "chat.emptyState.tpl.ocrExtract.prompt",
          color: "text-teal-600 dark:text-teal-400",
          bgColor: "bg-teal-50 dark:bg-teal-950/20",
        },
      ],
    },
    {
      id: "coding",
      labelKey: "chat.emptyState.categories.coding",
      emoji: "💻",
      templates: [
        {
          icon: Code2,
          titleKey: "chat.emptyState.tpl.codeHelp.title",
          descKey: "chat.emptyState.tpl.codeHelp.desc",
          promptKey: "chat.emptyState.tpl.codeHelp.prompt",
          color: "text-cyan-600 dark:text-cyan-400",
          bgColor: "bg-cyan-50 dark:bg-cyan-950/20",
        },
        {
          icon: Code2,
          titleKey: "chat.emptyState.tpl.codeDebug.title",
          descKey: "chat.emptyState.tpl.codeDebug.desc",
          promptKey: "chat.emptyState.tpl.codeDebug.prompt",
          color: "text-red-600 dark:text-red-400",
          bgColor: "bg-red-50 dark:bg-red-950/20",
        },
        {
          icon: Code2,
          titleKey: "chat.emptyState.tpl.codeExplain.title",
          descKey: "chat.emptyState.tpl.codeExplain.desc",
          promptKey: "chat.emptyState.tpl.codeExplain.prompt",
          color: "text-green-600 dark:text-green-400",
          bgColor: "bg-green-50 dark:bg-green-950/20",
        },
        {
          icon: Code2,
          titleKey: "chat.emptyState.tpl.codeConvert.title",
          descKey: "chat.emptyState.tpl.codeConvert.desc",
          promptKey: "chat.emptyState.tpl.codeConvert.prompt",
          color: "text-purple-600 dark:text-purple-400",
          bgColor: "bg-purple-50 dark:bg-purple-950/20",
        },
        {
          icon: Code2,
          titleKey: "chat.emptyState.tpl.sqlHelper.title",
          descKey: "chat.emptyState.tpl.sqlHelper.desc",
          promptKey: "chat.emptyState.tpl.sqlHelper.prompt",
          color: "text-amber-600 dark:text-amber-400",
          bgColor: "bg-amber-50 dark:bg-amber-950/20",
        },
        {
          icon: Code2,
          titleKey: "chat.emptyState.tpl.regexHelper.title",
          descKey: "chat.emptyState.tpl.regexHelper.desc",
          promptKey: "chat.emptyState.tpl.regexHelper.prompt",
          color: "text-indigo-600 dark:text-indigo-400",
          bgColor: "bg-indigo-50 dark:bg-indigo-950/20",
        },
      ],
    },
    {
      id: "translate",
      labelKey: "chat.emptyState.categories.translate",
      emoji: "🌐",
      templates: [
        {
          icon: Languages,
          titleKey: "chat.emptyState.tpl.translate.title",
          descKey: "chat.emptyState.tpl.translate.desc",
          promptKey: "chat.emptyState.tpl.translate.prompt",
          color: "text-sky-600 dark:text-sky-400",
          bgColor: "bg-sky-50 dark:bg-sky-950/20",
        },
        {
          icon: Globe,
          titleKey: "chat.emptyState.tpl.academicTranslate.title",
          descKey: "chat.emptyState.tpl.academicTranslate.desc",
          promptKey: "chat.emptyState.tpl.academicTranslate.prompt",
          color: "text-blue-600 dark:text-blue-400",
          bgColor: "bg-blue-50 dark:bg-blue-950/20",
        },
        {
          icon: PenTool,
          titleKey: "chat.emptyState.tpl.grammarCheck.title",
          descKey: "chat.emptyState.tpl.grammarCheck.desc",
          promptKey: "chat.emptyState.tpl.grammarCheck.prompt",
          color: "text-green-600 dark:text-green-400",
          bgColor: "bg-green-50 dark:bg-green-950/20",
        },
        {
          icon: MessageSquare,
          titleKey: "chat.emptyState.tpl.japaneseLearn.title",
          descKey: "chat.emptyState.tpl.japaneseLearn.desc",
          promptKey: "chat.emptyState.tpl.japaneseLearn.prompt",
          color: "text-red-600 dark:text-red-400",
          bgColor: "bg-red-50 dark:bg-red-950/20",
        },
        {
          icon: FileText,
          titleKey: "chat.emptyState.tpl.idiomExplain.title",
          descKey: "chat.emptyState.tpl.idiomExplain.desc",
          promptKey: "chat.emptyState.tpl.idiomExplain.prompt",
          color: "text-amber-600 dark:text-amber-400",
          bgColor: "bg-amber-50 dark:bg-amber-950/20",
        },
      ],
    },
    {
      id: "life",
      labelKey: "chat.emptyState.categories.life",
      emoji: "🎯",
      templates: [
        {
          icon: Plane,
          titleKey: "chat.emptyState.tpl.travelPlan.title",
          descKey: "chat.emptyState.tpl.travelPlan.desc",
          promptKey: "chat.emptyState.tpl.travelPlan.prompt",
          color: "text-sky-600 dark:text-sky-400",
          bgColor: "bg-sky-50 dark:bg-sky-950/20",
        },
        {
          icon: Utensils,
          titleKey: "chat.emptyState.tpl.recipeSuggest.title",
          descKey: "chat.emptyState.tpl.recipeSuggest.desc",
          promptKey: "chat.emptyState.tpl.recipeSuggest.prompt",
          color: "text-orange-600 dark:text-orange-400",
          bgColor: "bg-orange-50 dark:bg-orange-950/20",
        },
        {
          icon: Dumbbell,
          titleKey: "chat.emptyState.tpl.fitnessPlan.title",
          descKey: "chat.emptyState.tpl.fitnessPlan.desc",
          promptKey: "chat.emptyState.tpl.fitnessPlan.prompt",
          color: "text-green-600 dark:text-green-400",
          bgColor: "bg-green-50 dark:bg-green-950/20",
        },
        {
          icon: Stethoscope,
          titleKey: "chat.emptyState.tpl.healthAdvice.title",
          descKey: "chat.emptyState.tpl.healthAdvice.desc",
          promptKey: "chat.emptyState.tpl.healthAdvice.prompt",
          color: "text-red-600 dark:text-red-400",
          bgColor: "bg-red-50 dark:bg-red-950/20",
        },
        {
          icon: Heart,
          titleKey: "chat.emptyState.tpl.emotionSupport.title",
          descKey: "chat.emptyState.tpl.emotionSupport.desc",
          promptKey: "chat.emptyState.tpl.emotionSupport.prompt",
          color: "text-pink-600 dark:text-pink-400",
          bgColor: "bg-pink-50 dark:bg-pink-950/20",
        },
        {
          icon: Lightbulb,
          titleKey: "chat.emptyState.tpl.hobbyDiscover.title",
          descKey: "chat.emptyState.tpl.hobbyDiscover.desc",
          promptKey: "chat.emptyState.tpl.hobbyDiscover.prompt",
          color: "text-amber-600 dark:text-amber-400",
          bgColor: "bg-amber-50 dark:bg-amber-950/20",
        },
      ],
    },
];


export const TEMPLATES_BY_CATEGORY: Record<string, Template[]> = Object.fromEntries(
  CATEGORIES.map(c => [c.id, c.templates])
);
